config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  resources :books
  resources :publishers
  resources :autors do
    resources :books
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/autor.rb
class Autor < ApplicationRecord
    has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :autor
    belongs_to :publisher
end

app/models/publisher.rb
class Publisher < ApplicationRecord
    has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/autors_controller.rb
class AutorsController < ApplicationController
  before_action :set_autor, only: %i[ show edit update destroy ]

  # GET /autors or /autors.json
  def index
    @autors = Autor.all
  end

  # GET /autors/1 or /autors/1.json
  def show
  end

  # GET /autors/new
  def new
    @autor = Autor.new
  end

  # GET /autors/1/edit
  def edit
  end

  # POST /autors or /autors.json
  def create
    @autor = Autor.new(autor_params)

    respond_to do |format|
      if @autor.save
        format.html { redirect_to autor_url(@autor), notice: "Autor was successfully created." }
        format.json { render :show, status: :created, location: @autor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @autor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /autors/1 or /autors/1.json
  def update
    respond_to do |format|
      if @autor.update(autor_params)
        format.html { redirect_to autor_url(@autor), notice: "Autor was successfully updated." }
        format.json { render :show, status: :ok, location: @autor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @autor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /autors/1 or /autors/1.json
  def destroy
    @autor.destroy

    respond_to do |format|
      format.html { redirect_to autors_url, notice: "Autor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_autor
      @autor = Autor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def autor_params
      params.require(:autor).permit(:name, :age)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :set_autor

  def set_autor
    @autor = Autor.find(params[:autor_id]) #NO SE QUE HACE ESTO
  end

  # GET /books or /books.json
  def index
    @books = @autor.books
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save! #Para que arroje un error
        format.html { redirect_to autor_book_path(@autor.id, @book.id), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to autor_book_path(@autor.id, @book.id), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to autor_books_path(@autor.id), notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name, :autor_id, :publisher_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_action :set_publisher, only: %i[ show edit update destroy ]

  # GET /publishers or /publishers.json
  def index
    @publishers = Publisher.all
  end

  # GET /publishers/1 or /publishers/1.json
  def show
  end

  # GET /publishers/new
  def new
    @publisher = Publisher.new
  end

  # GET /publishers/1/edit
  def edit
  end

  # POST /publishers or /publishers.json
  def create
    @publisher = Publisher.new(publisher_params)

    respond_to do |format|
      if @publisher.save
        format.html { redirect_to publisher_url(@publisher), notice: "Publisher was successfully created." }
        format.json { render :show, status: :created, location: @publisher }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publishers/1 or /publishers/1.json
  def update
    respond_to do |format|
      if @publisher.update(publisher_params)
        format.html { redirect_to publisher_url(@publisher), notice: "Publisher was successfully updated." }
        format.json { render :show, status: :ok, location: @publisher }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publishers/1 or /publishers/1.json
  def destroy
    @publisher.destroy

    respond_to do |format|
      format.html { redirect_to publishers_url, notice: "Publisher was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publisher
      @publisher = Publisher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publisher_params
      params.require(:publisher).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/autors_helper.rb
module AutorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/autors/_autor.html.erb
<div id="<%= dom_id autor %>">
  <p>
    <strong>Name:</strong>
    <%= autor.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= autor.age %>
  </p>

</div>

app/views/autors/_form.html.erb
<%= form_with(model: autor) do |form| %>
  <% if autor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(autor.errors.count, "error") %> prohibited this autor from being saved:</h2>

      <ul>
        <% autor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/autors/edit.html.erb
<h1>Editing autor</h1>

<%= render "form", autor: @autor %>

<br>

<div>
  <%= link_to "Show this autor", @autor %> |
  <%= link_to "Back to autors", autors_path %>
</div>

app/views/autors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Autors</h1>

<div id="autors">
  <% @autors.each do |autor| %>
    <%= render autor %>
    <p>
      <%= link_to "Show this autor", autor %>
    </p>
  <% end %>
</div>

<%= link_to "New autor", new_autor_path %>

app/views/autors/new.html.erb
<h1>New autor</h1>

<%= render "form", autor: @autor %>

<br>

<div>
  <%= link_to "Back to autors", autors_path %>
</div>

app/views/autors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @autor %>

<div>
  <%= link_to "Edit this autor", edit_autor_path(@autor) %> |
  <%= link_to "Back to autors", autors_path %>
  <%= link_to "Ver libros del autor", autor_books_path(@autor.id) %>

  <%= button_to "Destroy this autor", @autor, method: :delete %>
</div>

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Nombre:</strong>
    <%= book.name %>
  </p>

</div>

app/views/books/_form.html.erb
<%= form_with(model: [@autor, book]) do |form| %> <!--Pero que es todo esto...-->
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :autor_id, style: "display: block" %>
    <%= form.collection_radio_buttons(:autor_id, Autor.all, :id, :name) %>
  </div>

  <div>
    <%= form.label :publisher_id, style: "display: block" %>
    <%= form.select :publisher_id, options_for_select(Publisher.all.pluck(:name, :id)) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", autor_book_path(@autor.id, @book.id) %> |
  <%= link_to "Back to books", autor_books_path(@autor.id) %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Libros de <%=@autor.name%></h1>

<div id="books">
  <% @books.each do |book| %>
    <%= render book %>
    <p>
      <%= link_to "Show this book", autor_book_path(@autor.id, book.id) %>
    </p>
  <% end %>
</div>

<p><%= link_to "New book", new_autor_book_path(@autor.id) %></p>
<%= link_to "Volver", autors_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", autor_books_path(@autor.id) %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Edit this book", edit_autor_book_path(@autor.id, @book.id) %> |
  <%= link_to "Back to books", autor_books_path(@autor.id) %>

  <%= button_to "Destroy this book", autor_book_path(@autor.id, @book.id), method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Librotienda</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;700&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark py-3">
      <!-- Container wrapper -->
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarCenteredExample" aria-controls="navbarCenteredExample" aria-expanded="false" aria-label="Toggle navigation">
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse justify-content-center" id="navbarCenteredExample">
          <!-- Left links -->
          <ul class="navbar-nav mb-2 mb-lg-0 ">
            <li class="nav-item d-flex align-items-center">
              <%= link_to 'Librería', root_path, class: 'nav-link fs-3 px-4 fw-bold text-white' %>>
            </li>
            <li class="nav-item d-flex align-items-center">
              <%= link_to 'Autores', autors_path, class: 'nav-link fs-6 px-4 text-white' %>
            </li>
            <li class="nav-item d-flex align-items-center">
              <%= link_to 'Editoriales', publishers_path, class: 'nav-link fs-6 px-4 text-white' %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container my-5"><%= yield %></div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/pages/index.html.erb
<h1>&#128218; Le damos la bienvenida a nuestro sistema de librerías &#128218;</h1>

app/views/publishers/_form.html.erb
<%= form_with(model: publisher) do |form| %>
  <% if publisher.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(publisher.errors.count, "error") %> prohibited this publisher from being saved:</h2>

      <ul>
        <% publisher.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/publishers/_publisher.html.erb
<div id="<%= dom_id publisher %>">
  <p>
    <strong>Name:</strong>
    <%= publisher.name %>
  </p>

</div>

app/views/publishers/edit.html.erb
<h1>Editing publisher</h1>

<%= render "form", publisher: @publisher %>

<br>

<div>
  <%= link_to "Show this publisher", @publisher %> |
  <%= link_to "Back to publishers", publishers_path %>
</div>

app/views/publishers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Publishers</h1>

<div id="publishers">
  <% @publishers.each do |publisher| %>
    <%= render publisher %>
    <p>
      <%= link_to "Show this publisher", publisher %>
    </p>
  <% end %>
</div>

<%= link_to "New publisher", new_publisher_path %>

app/views/publishers/new.html.erb
<h1>New publisher</h1>

<%= render "form", publisher: @publisher %>

<br>

<div>
  <%= link_to "Back to publishers", publishers_path %>
</div>

app/views/publishers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @publisher %>

<div>
  <%= link_to "Edit this publisher", edit_publisher_path(@publisher) %> |
  <%= link_to "Back to publishers", publishers_path %>

  <%= button_to "Destroy this publisher", @publisher, method: :delete %>
</div>